version: '3'
services:
    react-app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: trackify_client
        ports:
            - '5173:5173'

    express-server:
        build:
            context: ./backend
            dockerfile: Dockerfile
        container_name: trackify_server
        ports:
            - '3008:3008'
